/* 389. Find the Difference

Share
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added. */

// /**
//  * @param {string} s
//  * @param {string} t
//  * @return {character}
//  */
// var findTheDifference = function(s, t) {

//     var sMap = {};
//     var tMap = {};
//     var result = "";

//     for (var i =0; i< s.length; i++) {
//         sMap[s[i]] ? sMap[s[i]] += 1 : sMap[s[i]] = 1;
//     }

//     for (var i =0; i< t.length; i++) {
//         tMap[t[i]] ? tMap[t[i]] += 1 : tMap[t[i]] = 1;
//     }

//     console.log('sMap >>' , sMap);
//     console.log('tMap >>' , tMap);

//     for (let key in tMap) {
//         if(sMap[key]) {
//             if (tMap[key] - sMap[key] !== 0) {
//                 result += key.repeat(tMap[key] - sMap[key] );
//             }
//             console.log(sMap);
//         } else {
//             result += key;
//         }
//     }
//     console.log("result " , result);

//     return result;
// };

const findTheDifference_02 = (s, t) => {
    let map = {}
    for(const char of t){
        map[char] ? map[char]++ : map[char] = 1;
    }

    console.log('map >>> ' , map);

    for(const char of s){
        map[char]--
        if(map[char] === 0) delete map[char];
    }

    console.log('map >>> ' ,Object.keys(map)[0]);

    return Object.keys(map)[0]
};

  findTheDifference_02("abcd" , "abcdddeg");